In [2]:
import pandas as pd

In [3]:
restaurant_df = pd.read_csv("db_csv_preprocessed/restaurants_with_coords.csv")
menu_df = pd.read_csv("db_csv_preprocessed/menu_df.csv")
review_df = pd.read_csv("db_csv_preprocessed/review_df.csv")

## restaurant_df 구조 분석

In [4]:
restaurant_df.head()

,restaurant_code,restaurant_name,img_link,region,category,address,open_time,close_time,tel_no,tags,character,latitude,longitude
0,0,유태우스시,https://d12zq4w4guyljn.cloudfront.net/300_300_...,신대방삼거리역,"스시,회전초밥",서울특별시 동작구 보라매로 113 1층 유태우스시,11:00,22:00,0507-1358-1246,"데이트,혼밥","가성비좋은,서민적인,점심식사,저녁식사,바테이블,다찌석",37.499463,126.927897
1,1,듀윗,https://d12zq4w4guyljn.cloudfront.net/300_300_...,신대방삼거리역,"디저트,케이크",서울특별시 동작구 대방동1길 10 1층,08:00,21:00,0507-2093-6672,"데이트,기념일","예쁜,깔끔한,점심식사,테이크아웃,예약가능",37.500364,126.926712
2,2,한제소곱창전골 신대방삼거리역점,https://d12zq4w4guyljn.cloudfront.net/300_300_...,신대방삼거리역,"곱창전골,소곱창전골","서울특별시 동작구 여의대방로22길 121 상가동 1층 1444호, 1445호",16:00,00:00,0507-1359-9161,"술모임,해장용","지역주민이찾는,매콤한,저녁식사,예약가능,배달",37.499106,126.926924
3,3,프로스퍼,https://d12zq4w4guyljn.cloudfront.net/300_300_...,신대방삼거리역,"카페,커피",서울특별시 동작구 여의대방로24길 101 1층,10:00,00:00,0507-1361-3276,"차모임,혼자카페","캐주얼한,카공,점심식사,테이크아웃,와이파이",37.499088,126.925611
4,4,일진아구찜,https://d12zq4w4guyljn.cloudfront.net/300_300_...,신대방삼거리역,아구찜,서울특별시 동작구 여의대방로24길 93 1층,11:00,22:00,02-817-5554,가족외식,"서민적인,매콤한,점심식사,저녁식사,유아의자",37.498954,126.925189

In [5]:
tags = restaurant_df["tags"].unique()
tags = [t for t in tags if not pd.isna(t)]
buff = []
for t in tags:
    sublist = t.split(",")
    for s in sublist:
        buff.append(s)

tags = list(set(buff))
print(len(tags))
print(tags)

37
['전참시', '모범음식점', '모임장소', '해장', '다이어트식단', '소개팅장소', '간단히한잔', '실버푸드', '회식장소', '식신로드', '접대', '간단히먹기', '해장용', '식사모임', '혼자먹기', '생일파티', '혼자카페', '몸보신', '보양식', '낮술', '차모임', '모임', '소개팅', '생방송투데이', '송년회', '단체모임', '간단하게한잔', '데이트', '혼자먹기좋은', '술모임', '가족외식', '야식', '혼밥', '간식', '기념일', '혼술', '회식']

총 37개의 unique value가 존재하는 tag들

In [6]:
characters = restaurant_df["character"].unique()
characters = [c for c in characters if not pd.isna(c)]
buff = []
for c in characters:
    sublist = c.split(",")
    for s in sublist:
        buff.append(s)

characters = list(set(buff))
print(len(characters))
print(characters)

76
['동네사람', '카공', '서민적인', '예쁜', '연탄불', '지역주민이찾는', '반려동물동반', '셀프코너', '무료주차', '유아의자', '셀프바', '저녁식사', '바깥자리', '다찌석', '콜키지프리', '배달', '동네맛집', '예약', '여름보양식', '아담한', '아침식사', '점심맛집', '불맛', '비오는날', '테이크아웃', '매콤', '매콤한', '오빠랑', '개별룸', '안주', '매장식사', '국내산', '청결한', '아늑한', '가성비좋은', '깔끔한', '2차', '술안주', '무설탕', '한가한', '야장', '저렴한', '고급스러운', '야외테이블', '예약필수', '캐주얼한', '예약불가', '다양한반찬', '노포', '포장전문', '착한가격', '예약가능', '다양한메뉴', '칸막이', '크리스마스', '호주산', '바테이블', '콜키지', '야외테라스', '시끌벅적한', '저렴', '푸짐한', '얼큰', '좌식', '넓은테이블', '시원', '테라스', '연중무휴', '분위기좋은', '아기의자', '아기', '와이파이', '바자리', '야외자리', '점심식사', '넓은']

characters는 76개의 unique value가 존재

In [7]:
shared = set(tags) & set(characters)
print(shared)

set()

tag와 character의 역할은 비슷하지만 겹치는 값은 존재하지 않는 것으로 보임

## review_df 구조 분석

In [8]:
review_df.head()

,restaurant_code,reviewer_name,reviewer_avg_score,reviewer_rv_cnt,reviewer_follower_cnt,reviewer_score,taste_level,price_level,service_level,review_content,review_menu,keywords
0,0,냐밍,4.3,355,69,4점,2.0,2.0,1.0,요즘 회전초밥집 정말 비싼데 여긴 가성비 갑이었어요! 위치는 조금 복잡한 곳에 있긴...,회전초밥,"저녁식사,식사모임,캐주얼한,이국적/이색적,가성비좋은"
1,0,발통이,4.5,113,1,4점,1.0,2.0,2.0,한접시에 1500원이면 저렴해요 근데 맛도 생각보다 괜찮았어요! 엄청난 퀄리티는 아...,스시,"점심식사,지역주민이찾는"
2,0,우리의나날,4.5,420,2,5점,2.0,2.0,2.0,생일날 갔어요. 저녁시간 웨이팅있었지만 금방 자리에 앉았어요. 회전초밥 모든접시가 ...,회전초밥 1500원,"저녁식사,데이트,서민적인,푸짐한,지역주민이찾는"
3,0,냠냠냠히,4.8,71,0,5점,2.0,2.0,2.0,"모든접시 1,700원 이라는 가성비에 맛도 좋고 이런 굿굿!!","연어,장어","저녁식사,가성비좋은"
4,0,밍민,4.8,232,2,5점,2.0,2.0,2.0,1500원이라가성비좋아요 다양하게 먹을 수 있고 여러가지종류있어서 좋아요,회전초밥,"점심식사,캐주얼한"

In [9]:
keywords = review_df["keywords"].unique()
keywords = [k for k in keywords if not pd.isna(k)]
buff = []
for k in keywords:
    sublist = k.split(",")
    for s in sublist:
        buff.append(s)

keywords = list(set(buff))
print(len(keywords))
print(keywords)

61
['서민적인', '예쁜', '노키즈', '지역주민이찾는', '아침식사', '무료주차', '저녁식사', '다이어트식단', '배달', '동네맛집', '레트로', '부추전 제공', '실버푸드', '아담한', '기본안주 및 무료잔사케1인1잔제공', '야외좌석(테라스)', '7시이전 방문 1+1 이벤트', '접대', '24시간영업', '테이크아웃', '남녀구분화장실', '개별룸', '대기장소', '비오는날 미니김치전', '포장', '가성비좋은', '깔끔한', '식사모임', '아이동반', '고급스러운', '혼밥 존', '캐주얼한', '숨은맛집', '이국적/이색적', '콜키지무료', '지역주민이 찾는', '조용한', '혼카페', '여자끼리', '차모임', '친구들끼리', '디저트', '시끌벅적한', '주차불가', '푸짐한', '애완동물동반', '모던한', '데이트', '대형룸', '경관/야경이좋은', '술모임', '가족외식', '격식있는', '네이버예약시 생선튀김제공', '엄청맛있는', '점심식사', '혼밥', '간식', '기념일', '혼술', '회식']

In [10]:
print(set(keywords) & set(tags))
print(set(keywords) & set(characters))

{'데이트', '접대', '술모임', '가족외식', '회식', '다이어트식단', '간식', '차모임', '혼밥', '식사모임', '기념일', '혼술', '실버푸드'}
{'캐주얼한', '아담한', '예쁜', '서민적인', '아침식사', '지역주민이찾는', '테이크아웃', '무료주차', '개별룸', '저녁식사', '시끌벅적한', '배달', '동네맛집', '점심식사', '가성비좋은', '깔끔한', '푸짐한', '고급스러운'}

리뷰의 keyword와 tag, characteristic간에는 겹치는 값들이 확인됨

## category 테이블의 작성

In [11]:
categories = restaurant_df["category"].unique()
categories = [k for k in categories if not pd.isna(k)]
buff = []
for k in categories:
    sublist = k.split(",")
    for s in sublist:
        buff.append(s)

categories = list(set(buff))
print(len(categories))
print(categories)

123
['와플', '김밥', '제육쌈밥', '참치무한리필', '짜장면', '마라샹궈', '소갈비살', '순대국', '피자', '국밥', '횟집', '포차', '야끼니꾸', '일본가정식', '생선구이', '빵', '식빵', '일식당', '케이크', '한식', '바지락칼국수', '반찬가게', '닭발', '목살', '국물닭발', '대방어', '전집', '카츠', '분식', '김치닭볶음탕', '우설', '막걸리', '뼈해장국', '소곱창전골', '통닭', '이자카야', '떡볶이', '참치회', '쌈밥', '숙성회', '콩국수', '수제비', '호떡', '고기집', '중국집', '누룽지통닭', '소금구이', '소곱창', '아구찜', '닭꼬치', '곱창전골', '기계우동', '1인샤브', '베트남음식', '붕어빵', '회전초밥', '장어', '핫도그', '수제버거', '보리밥', '칼국수', '마라탕', '비빔밥', '포케', '닭갈비', '스시', '술집', '부타동', '후라이드', '곱창', '감자탕', '꼬치', '커피', '수박주스', '고깃집', '골뱅이소면', '오징어보쌈', '흑염소탕', '고추튀김', '꿔바로우', '장어구이', '검정콩국수', '디저트', '동태탕', '낙지비빔밥', '돌솥밥', '양념게장', '소고기국밥', '피맥', '타코야끼', '곱창볶음', '샤브샤브', '텐동', '묵은지', '돈까스', '오징어', '카페', '낙지', '주먹구이', '족발', '빙수', '젤라또와플', '밥집', '꽈배기', '낙지볶음', '갑오징어', '마카롱', '치킨', '연어초밥', '샐러드', '베트남쌀국수', '시래기불고기', '단팥죽', '젓갈전문', '돼지갈비', '테이크아웃카페', '보쌈', '생맥주', '피자집', '흑염소', '육전국밥', '직화낙지볶음', '게장']

In [12]:
category_df = pd.DataFrame(categories, columns=["category_name"])
category_df.head()

  category_name
0            와플
1            김밥
2          제육쌈밥
3        참치무한리필
4           짜장면

In [13]:
category_df.to_csv("db_csv_cat_tag/category.csv", index=False)

## tag 테이블의 작성

tag, character, 리뷰의 keyword가 비슷한 역할을 가졌으니 병합해서 tag 키워드로 관리

추가로 restaurant <> keyword 간의 N:M 관계 테이블을 정의

In [14]:
summed_tags = set(keywords) | set(tags) | set(characters)
print(len(summed_tags))

143

In [15]:
tag_df = pd.DataFrame(summed_tags, columns=["tag_name"])
tag_df.head()

             tag_name
0                저녁식사
1                 다찌석
2                회식장소
3  기본안주 및 무료잔사케1인1잔제공
4     7시이전 방문 1+1 이벤트

In [16]:
tag_df.to_csv("db_csv_cat_tag/tag.csv", index=False)