In [ ]:
!pip install -U langchain langchain-openai langchain-community

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.15)
Collecting langchain-openai
  Downloading langchain_openai-1.1.13-py3-none-any.whl.metadata (3.1 kB)
Collecting langchain-community
  Downloading langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.10 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.28)
Requirement already satisfied: langgraph<1.2.0,>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.1.6)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Collecting langchain-core<2.0.0,>=1.2.10 (from langchain)
  Downloading langchain_core-1.2.30-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: openai<3.0.0,>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (2.31.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (0.12.0)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community)
  Downloading langchain_classic-1.0.3-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.49)
Collecting requests<3.0.0,>=2.32.5 (from langchain-community)
  Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.13.5)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.13.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.7.30)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.23.0)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting langchain-text-splitters<2.0.0,>=1.1.1 (from langchain-classic<2.0.0,>=1.0.0->langchain-community)
  Downloading langchain_text_splitters-1.1.1-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (1.33)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (26.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.14.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (4.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.9 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (1.0.9)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (0.3.13)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (3.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (0.14.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (4.67.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.2.25)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.4.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2025.11.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.5->langchain) (1.12.2)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Downloading langchain_openai-1.1.13-py3-none-any.whl (88 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.7/88.7 kB 4.3 MB/s eta 0:00:00
Downloading langchain_community-0.4.1-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 19.9 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading langchain_classic-1.0.3-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 26.3 MB/s eta 0:00:00
Downloading langchain_core-1.2.30-py3-none-any.whl (513 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 513.0/513.0 kB 20.0 MB/s eta 0:00:00
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 3.0 MB/s eta 0:00:00
Downloading langchain_text_splitters-1.1.1-py3-none-any.whl (35 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 4.6 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: requests, mypy-extensions, marshmallow, typing-inspect, dataclasses-json, langchain-core, langchain-text-splitters, langchain-openai, langchain-classic, langchain-community
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
  Attempting uninstall: langchain-core
    Found existing installation: langchain-core 1.2.28
    Uninstalling langchain-core-1.2.28:
      Successfully uninstalled langchain-core-1.2.28
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.33.1 which is incompatible.
Successfully installed dataclasses-json-0.6.7 langchain-classic-1.0.3 langchain-community-0.4.1 langchain-core-1.2.30 langchain-openai-1.1.13 langchain-text-splitters-1.1.1 marshmallow-3.26.2 mypy-extensions-1.1.0 requests-2.33.1 typing-inspect-0.9.0

In [ ]:
from google.colab import userdata
import os

# os.environ에 담는 이유
# 우리가 가져다 쓰는 각 llm provider사들의 라이브러리 함수들이 첫 시작으로 자식의 key값을 os.environ에서 찾는 것이 첫 시작이기 때문

# os.environ['LANGSMITH_TRACING'] = 'true'
# os.environ['LANGSMITH_ENDPOINT'] = 'https://api.smith.langchain.com'
# os.environ['LANGSMITH_API_KEY'] = userdata.get('LANGSMITH_API_KEY')
# os.environ['LANGSMITH_PROJECT'] = "skn26_langchain"

os.environ['OPENAI_API_KEY'] = userdata.get('OPENAI_API_KEY')

해보자..

In [ ]:
import pandas as pd

In [ ]:
# menu_df 로드
menu_df = pd.read_csv("menu.csv")
menu_df = menu_df.fillna("")
menu_df.head()

,menu_code,restaurant_code,name,price,description,menu_desc,prompted_description,embedding_blobX,embedding
0,MEN0000,RES0000,회전초밥,,,회전초밥,회전초밥은 신선한 재료로 만든 다양한 초밥을 회전 컨베이어 벨트 위에서 편리하게 즐...,"[0.01146697998046875, -0.041229248046875, -0.0...",AOA7PADgKL0AYNS7ACAgPACAnzwAAO67AAC8uwBA5zwAII...
1,MEN0001,RES0000,장어초밥,,,장어초밥,"장어초밥은 부드럽고 고소한 장어가 신선한 초밥 위에 올려져 깊은 풍미를 자랑하며, ...","[-0.0072174072265625, -0.06524658203125, -0.00...",AIDsuwCghb0AoBe8AEBdPAAAZD0AAKq8AEBQuwDgET0AYP...
2,MEN0002,RES0001,프레지에 1호 홀케이크,50000.0,,프레지에 1호 홀케이크,"프레지에 1호 홀케이크는 신선한 재료로 정성껏 만든 부드럽고 촉촉한 케이크로, 특별...","[0.0193634033203125, -0.00444793701171875, -0....",AKCePADAkbsA4BS9AACeuwAgrz0AIBK9AOACvQDA9jwAIC...
3,MEN0003,RES0001,프레지에,10500.0,,프레지에,"프레지에는 부드러운 크림과 신선한 과일이 조화를 이루는 디저트로, 상큼하면서도 달콤...","[-0.0011615753173828125, -0.0180511474609375, ...",AECYugDgk7wAIIC9ACC8PABAFT0AIOE8AKBnvACAxT0AQJ...
4,MEN0004,RES0001,페르디셔 압펠,6000.0,,페르디셔 압펠,"페르디셔 압펠은 신선한 사과의 상큼한 맛과 부드러운 식감이 조화를 이루는 메뉴로, ...","[0.01401519775390625, -0.019989013671875, -0.0...",AKBlPADAo7wAoBO9AIBQvAAgqzwAwKK6AIAdvAAgQD0AYK...

In [ ]:
concat = list((menu_df["name"] + " " + menu_df["description"]).str.strip())
print(concat)

['회전초밥', '장어초밥', '프레지에 1호 홀케이크', '프레지에', '페르디셔 압펠', '루이보스 스트로베리 크림', '바바리안 민트', '아메리카노', '마카롱', '[패스오더전용] 100원 아메리카노 패스오더 앱 설치하면, 최소 주문 금액 없이 100원에 커피 주문+1,500원 쿠폰까지', '카페라떼', '카푸치노', '카페모카', '바닐라라떼', '임페리얼 얼그레이', '한제소곱창전골(소)', '한제소곱창전골 중 곱이 꽉꽉 차있는 소곱창과 깐양을 넣고 배추 버섯등을 듬뿍 넣은 맛있는 소곱창전골입니다', '한제소곱창전골 대 곱이 꽉 차있는 소곱창과 깐양을 넣고 배추 버섯등을 푸짐하게 넣어 국물이 진하고 맛있습니다', '한제소고기전골 소 사태를 넣고 배추 버섯등을 듬뿍 넣어 담백하고 깔끔합니다', '한제소고기전골 중 사태를 넣고 배추 버섯등을 듬뿍 넣어 담백하고 깔끔합니다', '한제소고기전골 대 사태를 넣고 배추 버섯등을 듬뿍 넣어 담백하고 깔끔합니다', '소곱창튀김 어디에서도 맛볼 수 없던 소곱창튀김입니다 한제의 다양한 소스에 찍어먹으면 꿀맛 !!', '한우수제떡갈비 수제로 만든 아이 어른 누구나 좋아하는 떡갈비', '도가니수육 남녀노소 모두가 좋아하는 건강식!', '한제수육 사태로 만든 술안주 끝판왕 수육', '에스프레소', '아메리카노', '밀크티', '민트초코라떼', '얼그레이', '페퍼민트', '캐모마일', '수제레몬청', '민트초코 프라푸치노', '피스타치오 아몬드 프라푸치노', '레몬에이드', '자몽에이드', '라떼', '수제 스트로베리 크럼블', '수제 당근케이크', '수제 치즈케이크', '수제 바스크치즈케이크', '수제 브라우니', '복숭아 아이스티', '빅토리아 케이크', '딸기크림', '피넛크림', '얼그레이크림', '바닐라라떼', '대파크림치즈', '누텔라크림', '카스테라크림', '카페라뗴', '카푸치노', '모카라떼', '크림커피', '초코 마들렌', '레몬 마들렌', '말차 마카다미아 쿠키', '초코 쿠키', '피스타치오크림', '오리지널치즈 [ P ] 4조각 토마토 소스 위에 모짜렐라 치즈', '페퍼로니 [ P ] 4조각 토마토 소스,모짜렐라 치즈,페퍼로니', '더블페퍼로니 [ P ] 4조각 토마토 소스,모짜렐라 치즈,페퍼로니', '무화과잼고르곤졸라 [ P ] 4조각 무화과 잼,모짜렐라,고르곤졸라 치즈', '통베이컨하와이안 [ P ] 4조각 토마토 소스,모짜렐라 치즈,통 슬라이스 파인과 통 베이컨', '모카 라떼', '치즈프라이피자 [ P ] 4조각 토마토 소스,모짜렐라 치즈,갓 튀김감자,달콤한 시럽,나초 소스,갈릭 디핑 소스,시즈닝,파슬리', '크리스콤보 [ P ] 4조각 토마토소스,모짜렐라 치즈,페퍼로니,구운 파프리카,양파,통옥수수,양송이,올리브,피망,수제 민찌,할라피뇨,미트 햄', '마스카포네바질 [ P ] 4조각 토마토 소스,모짜렐라 치즈,홈메이드 바질 페스토,마스카포네 치즈,그라나파다노', '갈릭디핑새우 [ P ] 4조각 토마토 소스,모짜렐라 치즈,통 새우,통 옥수수,수제 민찌,오크라,구운 파프리카,양파,피망,갈릭디핑 소스,미트햄', '라구루꼴라 [ P ] 4조각 토마토 소스,모짜렐라 치즈,양파,홈메이드 라구 루꼴라,그라나파다노,피망', '레귤러 하프앤하프', '오리지널치즈 [ R ] 6조각 토마토 소스 위에 모짜렐라 치즈', '페퍼로니 [ R ] 6조각 토마토 소스,모짜렐라 치즈,페퍼로니', '더블페퍼로니 [ R ] 6조각 토마토 소스,모짜렐라 치즈,페퍼로니', '무화과잼고르곤졸라 [ R ] 6조각 무화과 잼,모짜렐라,고르곤졸라 치즈', '통베이컨하와이안 [ R ] 6조각 토마토 소스,모짜렐라 치즈,통 슬라이스 파인과 통 베이컨', '치즈프라이 [ R ] 6조각 토마토 소스,모짜렐라 치즈,갓 튀김감자,달콤한 시럽,나초 소스,갈릭 디핑 소스,시즈닝,파슬리', '크리스콤보 [ R ] 6조각 토마토소스,모짜렐라 치즈,페퍼로니,구운 파프리카,양파,통옥수수,양송이,올리브,피망,수제 민찌,할라피뇨,미트 햄', '마스카포네바질 [ R ] 6조각 토마토 소스,모짜렐라 치즈,홈메이드 바질 페스토,마스카포네 치즈,그라나파다노', '라구루꼴라 [ R ] 6조각 토마토 소스,모짜렐라 치즈,양파,홈메이드 라구 루꼴라,그라나파다노,피망', '갈릭디핑새우 [ R ] 6조각 토마토 소스,모짜렐라 치즈,통 새우,통 옥수수,수제 민찌,오크라,구운 파프리카,양파,피망,갈릭디핑 소스,미트햄', '한국피자 [ R ] 6조각 토마토 소스, 모짜렐라 치즈, 피망, 적양파, 수제 불고기, 볶음김치', '한국피자 [ P ] 4조각 토마토 소스, 모짜렐라 치즈, 피망, 적양파, 수제 불고기, 볶음김치', '라지 하프앤하프', '오리지널치즈 [ L ] 8조각 토마토 소스 위에 모짜렐라 치즈', '초코라떼', '페퍼로니 [ L ] 8조각', '더블페퍼로니 [ L ] 8조각 토마토 소스,모짜렐라 치즈,페퍼로니', '무화과잼고르곤졸라 [ L ] 8조각 무화과 잼,모짜렐라,고르곤졸라 치즈', '통베이컨하와이안 [ L ] 8조각 토마토 소스,모짜렐라 치즈,통 슬라이스 파인과 통 베이컨', '치즈프라이피자 [ L ] 8조각 토마토 소스,모짜렐라 치즈,갓 튀김감자,달콤한 시럽,나초 소스,갈릭 디핑 소스,시즈닝,파슬리', '크리스콤보 [ L ] 8조각 토마토소스,모짜렐라 치즈,페퍼로니,구운 파프리카,양파,통옥수수,양송이,올리브,피망,수제 민찌,할라피뇨,미트 햄', '마스카포네바질피자 [ L ] 8조각 토마토 소스,모짜렐라 치즈,홈메이드 바질 페스토,마스카포네 치즈,그라나파다노', '라구루꼴라 [ L ] 8조각 토마토 소스,모짜렐라 치즈,양파,홈메이드 라구 루꼴라,그라나파다노,피망', '갈릭디핑새우 [ L ] 8조각 토마토 소스,모짜렐라 치즈,통 새우,통 옥수수,수제 민찌,오크라,구운 파프리카,양파,피망,갈릭디핑 소스,미트햄', '바질파스타 링귀니,홈메이드 바질 페스토,그라나파다노,레몬제스트,생 레몬', '녹차라떼', '토마토파스타 스파게티니, 직접 끓인 토마토 소스, 그라파다노 치즈', '봉골레파스타 스파게티니,산지 직송 조개,엔초비,마늘,양파,페퍼론치노,생 파슬리,마늘쫑', '한국 피자 [L] 8조각 토마토 소스, 모짜렐라 치즈, 피망, 적양파, 수제 불고기, 볶음김치', '잠봉크림파스타 딸리아뗄레,크림,체다 치즈,파마산 치즈,통 베이컨,쪽파,잠봉,만가닥 버섯', '라구파스타 푸질리,홈메이드 라구 소스,마늘,그라나파다노,루꼴라', '치즈 케익 8조각 홀 케익', '브라우니 케익 8조각 홀 케익', '당근 케익 8조각 홀 케익', '바스크 치즈 케익 8조각 홀 케익', '우유', '스트로베리 크럼블 케익 8조각 홀 케익', '시나몬 번', '아귀찜 소', '아귀찜 중', '아귀찜 대', '크림와플 와플대학만의 10가지 크림 중 원하는 맛을 골라 즐기는 와플', '애플시나몬와플 와플대학의 시그니처 메뉴로, 화이트크림에 사과잼과 시나몬 파우더를 더해 즐기는 와플', '토피토피넛 젤라또와플 고소한 아몬드와 호두가 바닐라 젤라또 속에 퐁당, 누텔라와 카라멜 시럽이 더해져 입안 가득 깊은 풍미가 번지는 와플', '스노우와플 와플대학만의 10가지 크림에 화이트크림을 더해 즐기는 와플', '메이플시나몬와플 달콤한 메이플 시럽에 시나몬 파우더를 더해 향긋한 와플', '추억의 사과잼 와플 밀크크림에 사과잼을 더한 추억의 와플', '추억의 딸기잼 와플 밀크크림에 딸기잼을 더한 추억의 와플', '해피 커스터드 바닐라빈와플 바닐라 빈이 들어가 부드러운 커스타드 크림을 듬뿍 담은 와플', '플레인와플 토핑없이 담백하고 바삭한 기본 와플', '해피 커스터드 코코넛와플 부드러운 커스터드 크림에 코코넛과 카라멜을 더해 이국적이고, 달콤한 풍미의 와플', '해피 커스터드 애플크림와플 부드러운 커스터드 크림에 애플시나몬 필링을 더해 애플파이를 오마주한 와플', '티라미수와플 와플로 만든 티라미수, 마스카포네치즈가 들어가 더 깊은 풍미로 즐기는 와플', '오레오누텔라와플 화이트크림에 누텔라와 초코크런치를 더해 누구나 맛있게 즐길 수 있는 와플', '치즈케이크&크랜베리와플 밀크크림에 치즈케이크와 크랜베리를 더해 상큼한 맛의 와플', '크런치딸기잼와플 화이트크림에 크런치 쿠키와 초코시럽, 딸기시럽을 더해 바삭하게 즐기는 와플', '호두고구마와플 화이트크림과 고구마무스, 호두로 식감까지 더한 든든하고 달콤한 와플', '팥스노우와플 화이트크림에 팥앙금과 연유를 더해 달콤하게 즐기는 와플', '허니브레드와플 화이트크림에 카라멜소스와 시나몬파우더를 더해 달콤하게 즐기는 와플', '와숫가루레드빈와플 팥앙금에 미숫가루를 더해 고소하고, 달콤하게 즐기는 와플', '베리베리케이크와플 와플로 만든 베리 케이크, 마스카포네 치즈에 블루베리와 크랜베리를 더해 새콤달콤하게 즐기는 와플', '모카케이크와플 와플로 만든 모카 케이크, 추억의 모카케이크에 크런치를 더해 바삭하게 즐기는 와플', '딸기케이크와플 와플로 만든 딸기 케이크, 화이트크림에 생딸기와 치즈케이크를 더해 진하게 즐기는 와플', '바나나와플 땅콩크림과 생바나나의 조화, 신선한 바나나의 맛을 즐길 수 있는 와플', '바나나누텔라와플 화이트크림에 누텔라와 생바나나를 더해 누구나 맛있게 즐길 수 있는 와플', '블루베리와플 화이트크림에 블루베리를 더해 달콤하게 즐기는 와플', '베리베리와플 화이트크림에 블루베리와 크랜베리를 더해 상큼 달콤한 와플', '딸기와플 밀크크림에 생딸기를 더해 신선한 딸기의 맛을 즐길 수 있는 와플', '딸기누텔라와플 화이트크림에 누텔라와 생딸기를 더해 누구나 맛있게 즐기는 와플대학의 스테디셀러 와플', '솜사탕 젤라또와플 솜사탕 젤라또에 톡톡 터지는 팝핑캔디를 더해 재미있게 즐기는 와플\r\n(보냉백 무상 제공)', '해피 커스터드 누텔라 젤라또와플 부드러운 커스터드 크림에 누텔라와 젤라또를 더해 시원하게 즐기는 와플', '치즈케이크누텔라젤라또와플 젤라또 와플에 누텔라와 치즈케이크를 더해 더 진하고 달콤하게 즐기는 와플\r\n(보냉백 무상 제공)', '오레오누텔라젤라또와플 젤라또 와플에 누텔라와 초코크런치를 더해 누구나 맛있게 즐길 수 있는 와플\r\n(보냉백 무상 제공)', '베리베리젤라또와플 젤라또 와플에 블루베리와 크랜베리를 더해 상큼 달콤하게 즐기는 와플\r\n(보냉백 무상 제공)', '블루베리젤라또와플 젤라또 와플에 블루베리를 더해 달콤하게 즐기는 와플\r\n(보냉백 무상 제공)', '더티초코케이크와플 와플로 만든 초코 케이크, 마스카포네 치즈에 초코를 가득 담아 깊은 풍미로 즐기는 와플', '크런치딸기잼젤라또와플 젤라또에 크런치와 초코시럽, 딸기시럽을 더해 달콤하고 바삭하게 즐기는 와플\r\n(보냉백 무상 제공)', '망고범벅젤라또와플 망고 젤라또에 망고 크림, 망고를 더해 망고의 풍미를 가득 즐길 수 있는 와플\r\n(보냉백 무상 제공)', '블루베리범벅젤라또와플 블루베리 요거트 젤라또에 블루베리 크림과 블루베리를 더해 블루베리의 풍미를 가득 즐길 수 있는 와플\r\n(보냉백 무상 제공)', '치즈범벅젤라또와플 치즈 젤라또에 치즈크림과 치즈 케이크를 더해 치즈의 풍미를 가득 즐길 수 있는 와플\r\n(보냉백 무상 제공)', '싸만코젤라또와플 젤라또에 팥앙금과 연유를 더해 달콤하게 즐기는 와플\r\n(보냉백 무상 제공)', '초코범벅젤라또와플 초코 젤라또에 초코 크림, 초코 시럽을 더해 초코의 달콤함을 가득 즐길 수 있는 와플\r\n(보냉백 무상 제공)', '크림젤라또와플 젤라또 와플에 와플대학만의 10가지 크림을 더해 즐기는 와플\r\n(보냉백 무상 제공)', '젤라또와플 바삭한 와플에 시원하고, 달콤한 젤라또를 더해 즐기는 와플\r\n(보냉백 무상 제공)', '딸기누텔라젤라또와플 젤라또 와플에 누텔라와 생딸기를 더해 누구나 맛있게 즐기는 와플대학의 스테디셀러 와플\r\n(보냉백 무상 제공)', '딸기범벅젤라또와플 생딸기에 딸기 젤라또, 딸기 크림을 더해 딸기의 풍미를 가득 즐길 수 있는 와플\r\n(보냉백 무상 제공)', '두바이초코와플 진한 초코크림과 고소한 피스타치오, 바삭한 카다이프가 듬뿍 들어가 달콤하고 고급스러운 프리미엄 와플', '솜사탕 젤라또컵 솜사탕 젤라또에 톡톡 터지는 팝핑캔디를 더해 재미있게 즐기는 젤라또 컵\r\n(보냉백 무상 제공)', '애플시나몬 젤라또컵 와플대학의 스테디셀러 애플 시나몬 와플을 시원하게 즐길 수 있는 젤라또 컵\r\n(보냉백 무상 제공)', '젤라또컵 토핑 없이 와플대학만의 10가지 젤라또 본연의 맛을 즐길 수 있는 젤라또 컵\r\n(보냉백 무상 제공)', '치즈케이크젤라또컵 와플대학만의 10가지 젤라또에 치즈케이크를 더해 진한 맛의 젤라또 컵\r\n(보냉백 무상 제공)', '크런치딸기잼젤라또컵 와플대학만의 10가지 젤라또에 크런치와 초코시럽, 딸기시럽을 더해 바삭하게 즐기는 젤라또 컵\r\n(보냉백 무상 제공)', '블루베리젤라또컵 와플대학만의 10가지 젤라또에 블루베리와 블루베리시럽을 더해 달콤하게 즐기는 젤라또 컵\r\n(보냉백 무상 제공)', '베리베리젤라또컵 와플대학만의 10가지 젤라또에 크랜베리와 블루베리, 딸기시럽을 더해 상큼하게 즐기는 젤라또 컵\r\n(보냉백 무상 제공)', '팥젤라또컵 와플대학만의 10가지 젤라또에 팥앙금과 연유, 미숫가루 파우더를 더해 고소하게 즐기는 젤라또 컵\r\n(보냉백 무상 제공)', '오레오젤라또컵 와플대학만의 10가지 젤라또에 초코크런치와 초코시럽을 더해 달콤하게 즐기는 젤라또 컵\r\n(보냉백 무상 제공)', '딸기젤라또컵 와플대학만의 10가지 젤라또에 생딸기와 딸기시럽을 더해 산뜻하게 즐기는 젤라또 컵\r\n(보냉백 무상 제공)', '두바이초코 스노우와플 진한 초코크림과 고소한 피스타치오, 바삭한 카다이프가 듬뿍. 화이트크림을 더해 더욱 부드럽고 고급스러운 프리미엄 와플', '아메리카노 와플대학만의 블랜딩으로 즐기는 아메리카노', '카페라떼 와플대학만의 블랜딩에 우유를 더해 부드럽게 즐기는 카페 라떼', '카페모카 와플대학만의 블랜딩에 초코를 더해 달콤하게 즐기는 카페 모카', '카라멜라떼 와플대학만의 블랜딩에 카라멜을 더해 달콤하게 즐기는 카라멜 라떼', '바닐라라떼 와플대학만의 블랜딩에 바닐라를 더해 달콤하게 즐기는 바닐라 라떼', '하얀 연유라떼 (HOT/ICE) 와플대학만의 블랜딩에 연유를 더해 부드럽고, 달콤하게 즐기는 하얀 연유 라떼', '디카페인 콜드브루 디카페인으로 즐기는 와플대학만의 디카페인 콜드브루', '디카페인 콜드브루 라떼 디카페인으로 즐기는 와플대학만의 디카페인 콜드브루 카페 라떼', '애플시나몬티 와플대학의 스테디셀러 애플 시나몬 와플을 차로 즐길 수 있는 애플 시나몬 티', '빨간 사과 유자차 빨간 애플티를 더해 향긋함이 2배 빨간 사과 유자차', '두바이초코 젤라또컵 초코젤라또와 피스타치오의 달콤한 조합, 바삭한 카다이프가 듬뿍 들어간 프리미엄 젤라또컵', '딸기 라떼(ICED ONLY) 국내산 논산 딸기를 사용해 더 달콤한 딸기 라떼', '캐모마일 부드럽고 은은한 캐모마일 차', '고구마라떼 고구마에 우유를 더해 달콤하고 든든한 고구마 라떼', '로얄밀크티라떼 홍차에 우유를 더해 부드럽고, 풍부한 풍미를 즐길 수 있는 로얄 밀크티 라떼', '그린티라떼 녹차에 우유를 더해 부드럽게 즐기는 그린티 라떼', '리얼초코라떼 초코에 우유를 더해 진한 초콜릿의 풍미를 즐길 수 있는 리얼 초코 라떼', '유자차 상큼 달콤한 유자차', '자몽차 달콤 쌉싸름한 자몽차', '베이비치노(Hot Only) 어린이 손님을 위해 준비한 따뜻한 우유', '(원액) 디카페인 콜드브루 300ml 어디서든 간편하게 즐길 수 있는 와플대학의 디카페인 콜드브루', '두바이초코 생딸기젤라또컵 초코젤라또와 피스타치오의 달콤한 조합, 상큼한 딸기와 바삭한 카다이프가 듬뿍 들어간 프리미엄 젤라또컵', '복숭아주스 향긋하고 달콤한 복숭아 주스', '자두에이드 새콤 달콤한 자두를 시원하게 즐길 수 있는 자두 에이드', '애플시나몬티에이드 와플대학의 스테디셀러 애플 시나몬 와플을 에이드로 즐길 수 있는 애플 시나몬 티 에이드', '와숫가루라떼(ICED ONLY) 와플대학만의 미숫가루 파우더에 우유를 더해 달콤하고, 든든하게 즐길 수 있는 와숫가루 라떼', '디카페인프라페(ICED ONLY) 디카페인 콜드브루에 부드러운 연유를 더해 시원하게 즐길 수 있는 디카페인 프라페', '딸기 에이드 달콤한 딸기를 시원하게 즐길 수 있는 딸기 에이드', '복숭아자두스무디 복숭아에 자두를 더해 향긋 상큼한 복숭아 자두 스무디', '딸기자두스무디 딸기에 자두를 더해 상큼 달콤한 딸기 자두 스무디', '플레인요거치노 상큼 달콤한 요거트를 시원하게 즐기는 플레인 요거치노', '블루베리요거치노 상큼 달콤한 요거트에 블루베리를 더해 시원하게 즐기는 블루베리 요거치노', '딸바누텔라 젤라또와플 딸기랑 바나나가 바닐라 젤라또 속에 퐁당, 누텔라와 풍부한 생과일이 만나 입안 가득 행복이 번지는 와플', '망고요거치노 상큼 달콤한 요거트에 망고를 더해 시원하게 즐기는 망고 요거치노', '복숭아요거치노 상큼 달콤한 요거트에 복숭아를 더해 시원하게 즐기는 복숭아 요거치노', '체리톡톡 체리콕에 톡 톡 터지는 팝핑 캔디를 더해 재미를 더한 체리 톡톡', '자두주스 새콤달콤한 자두 주스', '아쿠아레몬에이드 레몬 에이드에 파란색을 더해 눈으로도 즐길 수 있는 상큼한 아쿠아 레몬 에이드', '자몽에이드 달콤 쌉싸름한 자몽을 시원하게 즐길 수 있는 자몽 에이드', '청포도에이드 달콤한 청포도를 시원하게 즐길 수 있는 청포도 에이드', '복숭아에이드 향긋한 복숭아를 시원하게 즐길 수 있는 복숭아 에이드', '복숭아아이스티 남녀노소 누구나 사랑하는 달콤하고, 시원한 복숭아 아이스티', '숯불 무뼈닭발(맵기 중) 중급자용 맛있게 매운맛', '통뼈 국물닭발(맵기 중) 닭발 초급자용 매운맛\r\n사리 추가시 +2,000원', '5. 아무거나 셋트(단품1+단품2+계란찜) (단품1+단품2+계란찜)\r\n33,000원 부터~', '숯불 통뼈닭발(맵기 최상) 눈물나게 매운맛', '똥집튀김 안매움', '국물떡볶이', '대접 계란찜', '녹두 빈대떡', '김치말이 냉국수', '날치알 주먹밥(한 대접)', '공기밥', '무뼈닭발용 야채추가(1봉)', '오돌뼈+날치알주먹밥+사각김 오돌뼈+김가루주먹밥+싸먹는김', '국물닭발용 콩나물추가(1봉)', '자두맛 샤벳쿨피스(930ml)(930ml)', '떡사리(국물닭발,닭도리탕,떡볶이)', '우동사리(국물닭발,닭도리탕,떡볶이)', '당면사리(국물닭발,닭도리탕,떡볶이)', '비엔나소세지 사리(국물닭발,닭도리탕,떡볶이)', '오뎅사리(국물닭발,닭도리탕,떡볶이)', '사이다(PT 소)', '코카콜라(PT 소)', '닭도리탕 불맛나는 닭도리탕\r\n사리추가시 +2,000원', '소금구이 볶음똥집 불맛나는 환상적인 별미', '무뼈 국물닭발(맵기 하) 닭발 초급자용 매운맛\r\n사리 추가시 +2,000원', '1. 숯불 통뼈닭발 셋트 통닭발+오돌뼈+날치알주먹밥+사각김+계란찜', '2. 숯불 무뼈닭발 셋트 무뼈닭발+오돌뼈+날치알주먹밥+사각김+계란찜', '3. 통뼈 국물닭발 셋트 국물닭발+오돌뼈+날치알주먹밥+사각김+계란찜', '4.무뼈 국물닭발 셋트 무뼈국물닭발+오돌뼈+날치알주먹밥+사각김+계란찜', '콩국수', '검정콩국수', '노란콩물 0.9L (포장)', '콩칼국수', '검정콩칼국수', '바지락칼국수', '들깨수제비', '만두', '파전', '검정콩물 0.9L (포장)', '검정콩물 1.5L (포장)', '콩나물국밥', '김치콩나물국밥', '제육비빔밥', '강된장비빔밥', '소불고기비빔밥', '뚝배기불고기', '고추장 제육볶음', '육전', '맛보기전', '김치전', '메밀부추전', '녹두전', '만두콩나물국밥', '해물파전', '모듬전', '고추장찌개', '편육', '떡갈비', '메밀전병', '모듬만두', '왕만두', '만두김치콩나물국밥', '황태콩나물국밥', '굴국밥', '해물순두부찌개', '백합콩나물국밥', '전주비빔밥', '쭈꾸미비빔밥', '등심 150g', '한우주물럭 150g', '영양갈비탕', '돌솥비빔밥', '산채비빔밥', '마포소갈비5대', '한우육회 180g', '돼지갈비 250g', '삼겹살 150g', '목살소금구이150g', '허브삼겹살150g', '물냉면', '비빔냉면', '대방어 회 한상 (예약추천) 대방어회 시작\r\n기본\r\n뚝배기오뎅탕,초밥용 밥,간장새우,회무침,샐러드,팥빙수가 제공됩니다.', '대삼치 회 한상(예약추천) 기본\r\n뚝배기오뎅탕,초밥용 밥,간장새우,회무침,샐러드,팥빙수가 제공됩니다.', '모듬 회덮밥', '모리 특선 초밥 11p 초밥 주문시\r\n기본 3찬 + 샐러드 +국물 제공됩니다.', '모리 시그니쳐vip 초밥 초밥 주문시\r\n기본 3찬 + 샐러드 +국물 제공됩니다.', '물회', '※※※그밖에 안주 및 사이드※', '닭껍질교자', '치킨 가라아게', '가쓰오 김치 오뎅탕', '가쓰오 오뎅탕', '먹태구이', '생선메뉴는 가격변동이 있을수 있습니다', '뚝배기 김치어묵우동', '치즈 불닭게티', '치즈 짜파구리', '철판김치볶음밥', '모찌리도후', '파인샤베트', '모듬고로케 6P', '왕새우튀김 3P', '청어알젓(60g) 추가', '준마이 북극곰의 눈물 720ml', '※※※메인 안주류※', '간바레오토상 팩', '하쿠쯔루 마루', '센300', '모리 하이볼', '짐빔 하이볼', '느린마을 늘봄 막걸리', '서울의밤', '일품진로 SET 일품진로+토닉워터2개+레몬', '화요25 SET 화요25+토닉워터2개+레몬', '서울의 밤 SET 서울의밤+토닉워터 2개+레몬', '※※※※※※※※※※※※', '도원결의 SET 도원결의+토닉워터2개+레몬', '2+1 하이볼 SET', '소주 후레쉬, 진로이즈백, 처음처럼, 새로', '새로살구', '참이슬 오리지널', '한라토닉 세트', '한라산', '병맥주 테라, 카스, 켈리', '청하', '토닉워터', '모듬숙성회 한상 기본으로\r\n뚝배기오뎅탕,초밥용 밥,간장새우,회무침,샐러드,팥빙수가 제공됩니다.', '대방어+참돔 반반 한상 기본으로\r\n뚝배기오뎅탕,초밥용 밥,간장새우,회무침,샐러드,팥빙수가 제공됩니다.', '대방어+대삼치 회 한상(예약추천) 대방어회 시작\r\n기본\r\n뚝배기오뎅탕,초밥용 밥,간장새우,회무침,샐러드,팥빙수가 제공됩니다.', '통삼겹 수육튀김', '※※※초밥 및 식사류※', '장어소금구이(1kg) 장어 구이 입니다.', '장어추가(500g) 장어 추가 주문시 500g단위로 가능합니다.', '갑오징어(구이/숙회) 구이 또는 숙회로 즐길 수 있는 갑오징어로 탱탱하여 맛이 아주 좋습니다.', '가리비구이(계절메뉴) 계절 메뉴 가리비 구이로 탱탱한 가리비 구이를 맛보실 수 있습니다.', '꼬장세트(꼬막비빔밥+미니장어탕) 밑반찬과 함께 든든히 즐길 수 있는 꼬막비빔밥과 장어탕입니다. 맛있게 즐겨주세요', '장어탕 장어로 맛있게 우려낸 장어탕입니다.', '꼬막비빔밥 꼬막이 풍부하고 새콤한 꼬막비빔밥입니다.', '아뜨레국산팥빙수', '아뜨레흑임자빙수', '샤인머스켓요거트조각', '통고구마조각', '생딸기조각', '얼그레이헤이즐넛갸또', '블루베리치즈케이크', '조각모둠케이크 매장에 있는 조각케이크 7개합쳐 원형.\r\n레터링은 서비스입니다', '카페라떼', '마시멜로핫초코', '런던포그', '딸기폭탄케이크 1호 57000\r\n2호 63000\r\n미리 주문주셔야 합니다', '아뜨레생딸기빙수 계절메뉴', '안녕딸기케이크 하루 전 미리 주문주셔야 가능합니다\r\n계절메뉴\r\n2호 52000\r\n1호 50000', '생망고홀케이크 1호 54000\r\n2호 56000\r\n미리 주문주셔야합니다', '개인레터링케이크 원하시는 디자인 알려주시면 가능여부와 금액 알려드릴수있어요\r\n미리 주문주셔야합니다', '인물케이크 2호 52000\r\n사진주시면그려드리는인물케이크\r\n미리 주문주셔야합니다', '계란한판케이크 1호 53000\r\n2호 55000\r\n미리 주문주셔야합니다', '왕관케이크 2호 53000\r\n3호 63000\r\n미리 주문주셔야합니다', '솔드아웃케이크 2호 5만\r\n3호 6만\r\n미리 주문주셔야합니다', '해리포터케이크 1호 38000\r\n2호 40000\r\n3호 50000', '축구공케이크 2호 70000\r\n3호 80000\r\n미리 주문주셔야합니다', '지하철케이크 2호 50000\r\n3호 60000\r\n꽃테두리\r\n2호 63000\r\n3호 73000', '홍시빙수 1년 내내 홍시빙수', '소주케이크 원형2호 5만\r\n3호 6만\r\n네모 소주케이크 7만\r\n미리 주문주셔야합니다', '나이스샷케이크 2호 70000\r\n3호 80000', 'TNT케이크 2호 70000\r\n3호 80000\r\n미리 주문주셔야합니다', '인물꽃케이크 2호 65000\r\n3호 75000\r\n미리 주문주셔야합니다', '로또케이크 2호 52000\r\n3호 62000\r\n꽃 테두리\r\n2호 65000\r\n3호 75000', '생화케이크 기본7만부터~\r\n꽃 싯가 변동에 따라 달라요\r\n미리 주문주셔야합니다', '꽃다발케이크 2호 70000\r\n3호 80000\r\n미리 주문주셔야합니다', '환갑칠순팔순케이크 2호 58000\r\n3호 68000\r\n미리 주문주셔야합니다', '골드바케이크 2호 70000\r\n3호 80000\r\n미리 주문주셔야합니다', '달력케이크 2호 5만\r\n3호 6만\r\n미리 주문주셔야합니다', '생망고빙수 계절메뉴', '포토케이크 2호 52000\r\n3호 62000\r\n미리 주문주셔야합니다', '초미니도시락케이크 그림은 안그려드려요\r\n당일케이크도 미리 주문해주셔야 픽업 가능합니다', '샤인머스켓빙수 계절메뉴', '생메론빙수 계절메뉴', '무화과빙수 계절메뉴', '블루베리가나슈조각', '생망고조각케이크', '수제튀김 고구마 단호박 김말이 오징어 만두', '떡볶이', '참치김밥', '치즈김밥', '돈가스김밥', '순대 내장미포함', '부산어묵', '풀세트 떡볶이+순대+튀김5+어묵+음료', '떡튀순세트 1인분 / 떡볶이+튀김5+음료', '떡순어세트 떡볶이+순대+어묵', '모듬A세트 떡볶이+모듬튀김+순대+어묵+음료수', '모듬B세트 떡볶이+모듬튀김+순대+유부주머니+음료수', '야채김밥', '원조한판 육즙목살 ,숙성 삼겹살 ,쫀득살(600g) 2~3인 세트 한판 골고루 맛보러 오세요~!', '특수한판 갈매기살 , 가브리살 , 쫀득살 부안집 특수부위 총출동! 신메뉴 출시했습니다~!', '부안철판볶음밥 마무의리~철판볶음밥!\r\n파김치다데기로 맛있게 볶아\r\n긁어먹는 재미로 기쁨두배♡', '계란찜 폭탄계란찜~!\r\n아이들도 좋아하는 계란~찜\r\n꼭 먹어보자♡', '비빔냉면 물냉이 있으면 당연히 비냉도 있어야지^^\r\n일단 시켜보자~물냉만큼 맛있다', '물냉면 고기와 찰떡궁합~!\r\n여름에는 물냉이 최고♡', '살얼음 물쫄면 입안의 느끼함을 잡아줄수있는 살얼음 동동 물쫄면', '파절이쫄면 웬만한 분식집보다 맛있는 원조부안집의 사이드메뉴', '대파라면 대파김치가 듬뿍! 얼큰시원 라면', '짜파게티 짜짜짜짜파게티~! 오늘은\r\n내가 짜파게티 요리사♡', '10분밥 좋은 쌀로 갓 지은 밥으로 버터, 계란 , 참기름, 등을 비벼 먹는 시그니처 메뉴', '양푼김치찌게 매장에서 직접끓여 개운하고 얼큰한 부안식 김치찌개', '육즙목살 🏆"대한민국 3대목살"\r\n📌육즙이 터져나오는 부드러운 목살', '쫀득살 🏆"원조부안집 시그니처 메뉴"\r\n📌피자모양의 쫀득쫀득한 특수부위 끝판왕', '숙성삼겹 🏆"대한민국 대표 메뉴"\r\n📌저희 매장은 1++ 삼겹살만을 사용합니다.', '갈매기살 대한민국에서 제일 신선한\r\n국내산 양막 생갈매기살♡\r\n한정판매!!', '등겹살(가브리살) 국내산 가브리살(등겹살)\r\n등심덧살부위로 부드러움의 끝판왕♡\r\n요것도 한정판매!!', '원조숯불갈비 🏆"역대급 중량 250g"\r\n📌씹고 뜯는 맛이 일품인 진짜 뼈가 붙은 국내산 양념갈비', '쫄깃껍데기 🏆"단골손님들 원픽"\r\n📌특제 간장소스에 숙성하여 쫄깃하면서 고소하다.', '부안된장술밥 주당들의 최애메뉴♡\r\n매장에서 직접끓여 더욱\r\n맛있고 깔끔^^', '훈연 베이징덕 훈제오리에 특제 소스를 발라 담백하게 구워 밀전병과 함께 싸먹는 요리(+대파,오이,청꼬)', '게내장 크림 우동파스타 영덕대게 내장을 넣은 고소하고 녹진한 크림 우동', '육토마끼 오다 시그니처인 한우육회를 듬뿍 넣어 연어와 함께 말아낸 후토마끼 자매버전', '생연어카르파쵸발사믹샐러드', '슈프림양념가라아게 슈프림양념소스에 버무린 가라아게', '불닭우삼겹야끼우동 불닭소스에 각종야채, 우삼겹, 우동면을 불향나게 볶아낸 한국식 매운야끼우동', '우삼겹탄탄나베(면포함)', '돈코츠나베(면포함)', '치즈x4 불닭볶음면 불닭볶음면에 네가지 치즈가 올라가요!', '붉은볼락튀김 붉은볼락튀김', '우삼겹 마라샹궈 얼얼한 마라소스에 우삼겹, 채소, 중화면을 불 맛나게 볶아낸 중화풍 볶음요리', '우니한판 녹진한 우니를 오이, 감태, 초밥 밥과 곁들여 먹는요리', '치킨난반 부드러운 통닭다리 살을 특제소스에 재워 튀겨 타르타르 소스와 곁들여 먹는 요리', '묵,치,김볶밥 묵은지와 삼겹살을 매콤하게 볶은 마성의 김치볶음밥(feat. 치즈와 후라이)', '게살크림고로케 게살의 풍미와 부드러운 크림이 어우러진 고로케', '닭껍질교자 닭껍질 안에 여러가지 채소와 고기를 넣어서 튀겨낸 겉바속촉 핑거푸트', '타코와사비 낙지와 주꾸미를 고추냉이에 버무려 오이, 김과 함께 곁들여 먹는 요리', '트러플 감자튀김 감자튀김과 트러플의 콜라보', '파인애플샤베트 파인애플을 통으로 얼린 상큼x시원 샤베트', '트러플 짜파게티 트러플향 가득한 짜파게티에 노른자와 치즈를 올려 고소함을 극대화!', '우니,단새우,관자,육회 사합 우니,단새우,관자,육회를 감태에 싸먹는 사합요리', '우니,단새우,관자삼합 분홍단새우, 가리비관자, 우니, 연어알 등을 구운감태와 함께 곁들여 먹는 요리', '훈연삼치봉초밥', '홍가리비술찜 +파스타면', '광어묵은지소금김밥(8p) 광어묵은지소금김밥(8p)', '우니파스타', '후토마끼 참치,연어,계란말이,새우튀김,유부 등의 속재료를 푸짐하게 넣어 말아낸 왕김밥', '바지락칼국수', '갑오징어명란불고기 갑오징어, 명란, 각종 야채와 볶음소스가 어우러진 매콤달콤한 맛', '반반튀김(갑오징어/새우) 갑오징어와 새우가 반반인 깔끔하고 고소한 튀김', '갑오징어튀김 바삭하고 고소한 갑오징어튀김', '갑삼불고기백반 갑오징어와 삼겹살, 볶음소스와 각종 야채가 어우러진 매콤달콤한 맛', '갑오징어불고기백반 갑오징어와 볶음소스, 각종 야채가 어우러진 매콤달콤한 맛', '갑삼불고기 갑오징어와 삼겹살, 볶음소스와 각종 야채가 어우러진 매콤달콤한 맛', '갑오징어초무침 갑오징어와 각종 야채, 양념초장이 어우러진 매콤하고 상큼한 맛', '갑오징어연포탕 갑오징어와 육수, 각종 해산물과 야채가 어우러진 담백하고 시원한 국물', '갑오징어불고기 갑오징어와 각종 야채, 볶음소스가 어우러진 매콤달콤한 맛', '오삼불고기백반 오징어와 삼겹살, 볶음소스와 각종 야채가 어우러진 매콤달콤한 맛', '가리비게살튀김 가리비살과 게살로 만든 부드럽고 고소한 튀김', '칼국수', '칼만두', '칼제비', '손만두', '콩국수 계절메뉴', '우동', '짜장', '짜장밥', '곱배기', '두부김치', '부추전', '잔치국수', '짜장면', '짬뽕', '간짜장', '짬뽕밥', '볶음밥', '부타동 돼지고기 덮밥.', '토리동 닭다리살 덮밥.', '마제소바 일본식 비빔면.', '탄탄멘 중국식 라멘', '숙주번데기탕', '술탄치즈', '우육탕', '크림새우', '부추두부김치', '연어사시미', 'A set(반반치킨+더블페퍼로니피자)', 'B set(순살반마리+8인치페퍼로니)', '순살 양념치킨', '순살크리스피 양념 반반', '순살양념치즈치킨', '순살 볼케이노 치즈치킨', '닭꼬야끼', '닭날개 튀김(6조각)', '빅사이즈 4가지 피자', '스윗베이컨고구마&고르곤졸라', '베이컨체다치즈&더블페퍼로니', '바베큐불고기피자', 'C set(순살반마리+8인치스윗고구마)', '베이컨치즈후라이피자', '고르곤졸라피자', '더블페페로니피자', '스윗베이컨고구마피자', '베이컨체다치즈피자', '8인치 페파로니피자', '8인치 스윗고구마피자', '아이스황도', '파인애플샤벱', '오징어&땅콩', '마늘간장날개(12조각)', '달맥 먹태구이', '달맥 한치구이', '달맥 쥐포구이', '골뱅이무침&쫄면', '로스팅소세지&포테이토', '매콤 핫 닭발', '페스츄리소세지', '달맥 부대찌개', '통오징어해물탕(우동사리포함)', '달맥 어묵탕', '순살마늘간장 치킨', '달맥 떡볶이', '달맥 김치우동', '닭똥집튀김', '닭똥집 양념튀김', '모듬튀김', '김말이튀김', '야채튀김', '잡채만두튀김', '달콤우유튀김', '드래곤치즈볼', '후라이드 치킨', '롱오징어튀김', '롱새우튀김', '어니언링튀김', '새우링튀김', '닭껍질튀김', '케이준포테이토', '브라운어니언프라이드', '생맥주 300cc', '생맥주 500cc', '블랑 생맥주', '양념치킨', '기린 생맥주', '시나몬 코젤다크', '코젤다크', '달맥 하이볼(토닉)', '달맥 하이볼(진저)', '달맥 홍이볼(얼그레이)', '하이볼 샷추가', '소주', '제로콜라', '사이다', '후라이드 양념 반반', '콜라', '매운바베큐치킨', '순살크리스피치킨', '베이컨김치두부 베이컨, 볶음김치와 두부김치의 환상궁합', '마늘목살볶음 대표메뉴☆ 드셔보세요. 짭조롬한 목살볶음', '닭도리탕 국내산 닭도리탕 바로조리합니다.(시간소요)', '부추전 부추전☆', '김치전 한국인의 맛 / 김치전', '무뼈닭발 철판 무뼈닭발', '오징어볶음 오징어와 소면을 한입에 앙앙', '골뱅이무침 새콤달콤한 골뱅이+소면을 앙앙', '모듬소세지 청송만의 수제 모듬소세지☆ (타 음식점과의 차별화된 소세지의 맛)', '도토리묵 무침 막걸리와 최고의 궁합', '닭똥집볶음 채소와 곁들인 똥집볶음 & 소금기름장', '야채계란말이 우와,푸짐한 계란말이☆ 한입앙앙', '고기전 고기반죽부터 직접 100% 작업하여 만드는 청송의 시그니처 메뉴입니다.', '생선구이SET 가자미,고등어,삼치,임연수 세트', '과일화채 과일과 달달한 우유의 만남(계절에 따라 과일이 달라요)', '과일황도 황도와 함께 계절에 맞는 과일', "옛날도시락 옛날 학창시절의 추억의 도시락(1970's)", '잔치국수 맛있는 사이드 메뉴', '해장라면 사이드 메뉴', '감자전 바로 갈아서 만드는 감자전 한입앙앙', '얼큰김치수제비 직접만드는 저온숙성 수제비☆반죽 얼큰하게 드셔보세요.', '맑은감자수제비 직접 만드는 저온숙성 수제비☆반죽 맑고 시원하게 드셔보세요.', '바지락수제비 직접 만드는 저온숙성 수제비☆반죽 / 바지락', '만수탕 만두+ 수제비+ 순두부 든든하게 먹을수 있는 청송의 시그니처 메뉴입니다', '녹두전 100% 수제녹두반죽입니다 ☆ 한입앙앙', '모듬전 여러가지 전을 한번에 드실수 있습니다.\r\n(고기,김치,동태,녹두,호박,버섯,두부,꼬지,햄)', '날치알 주먹밥 날치알주먹밥 ( 날치알과 볶음김치의 만남 )', '오삼불고기 오삼불고기 매콤하고 오징어와 삼겹살의 만남', '두부김치 두부와 김치 만남 ( 남녀노소 편하게 먹을수있는 안주 )', '해물누룽지탕 시원하고 살짝 얼큰한 해물누룽지탕 ( 해물과 누룽지과자 조합 )', '골뱅이무침 골뱅이무침과 소면', '연어샐러드 훈제연어와 야채 그리고 시큼한\r\n맛의 조합', '해물찜 해물과 매콤한 양념의 맛!\r\n해물찜', '(오픈 즉시 할인)대한민국 대표 마라탕(1인분) 먹어도먹어도 질리지않는 불가사의한 맛', '(오픈 즉시 할인)대한민국 대표 마라탕(2~3인분) 먹어도먹어도 질리지않는 불가사의한 맛', '치킨X 겉바속촉 꿔바로우(대 (15p)) 톰과 제리처럼 새콤달콤궁합', '양저우볶음밥(1인분) 담백한 맛이 일품인 계란볶음밥', '펩시콜라(355ml)', '제로콜라(펩시)(355ml)', '사이다(355ml)', '립톤아이스티복숭아(355ml)', '빙홍차(490ml)', '[ 즉시 할인 ]셀프 마라탕(+++ 기본 소고기 100g +++) [ 기본 9,900원 부터 주문가능 ]\r\n기본재료 NO, 모든재료 내 취향대로 고르기', '[ 즉시 할인 ]셀프 마라탕(+++ 기본 숙주 100g +++) [ 기본 9,900원 부터 주문가능 ]\r\n기본재료 NO, 모든재료 내 취향대로 고르기', '고기 일품 마라샹궈 (고기O)(1인분) 마라향과 불맛의 향연, 독보적인 중독성', '고기 일품 마라샹궈 (고기O)(2~3인분) 마라향과 불맛의 향연, 독보적인 중독성', '[] 내맘대로 [] 셀프 마라샹궈(+++ 기본 소고기 100g +++) [기본 15,900원 부터 주문가능]\r\n기본재료 NO, 모든재료 내취향대로 고르기\r\n마라샹궈는 최소주문금액 15,900원 이하 주문시 주문취소 됩니다.', '[] 내맘대로 [] 셀프 마라샹궈(+++ 기본 숙주 100g +++) [기본 15,900원 부터 주문가능]\r\n기본재료 NO, 모든재료 내취향대로 고르기\r\n마라샹궈는 최소주문금액 15,900원 이하 주문시 주문취소 됩니다.', '치킨X 겉바속촉 꿔바로우(미니 (5p) 소스 따로 불가능) 톰과 제리처럼 새콤달콤궁합', '치킨X 겉바속촉 꿔바로우(중 (10p)) 톰과 제리처럼 새콤달콤궁합', '뼈다귀전골(소) 우거지+감자+수제비+깻잎+팽이버섯\r\n(서비스 라면사리는 반조리 선택시만 제공)', '뼈다귀전골(중) 우거지+감자+수제비+깻잎+팽이버섯\r\n(서비스 라면사리는 반조리 선택시만 제공)', '뼈다귀전골(대) 우거지+감자+수제비+깻잎+팽이버섯\r\n(서비스 라면사리는 반조리 선택시만 제공)', '뼈해장국(2인) 공기밥 포함', '뼈해장국(3인) 공기밥 포함', '뼈해장국(1인)(1인) 공기밥 포함', '공기밥', '왕만두(4개)', '사이다(500ml)', '콜라(500ml)', '모둠사시미(어종수시변동) 제철마다 오는 다양한 어종의 생선을 내어드리는 대표메뉴입니다', '밀푀유나베 천개의 꽃이라불리는 밀푀유나베 탕냄비가 모자랄 만큼 꽉꽉채워드리는 단길 대표메뉴입니다', '양념닭목살볶음', '통가지새우튀김', '통새우 부추전', '유린기', '들기름 깻잎 돌문어 무침', '수제 가라아게', '베이컨 청양크림파스타', '가시바른순살삼치구이', '치즈계란말이', '알찬열빙어구이', '곱도리탕', '명란구이', '카라이돈코츠라멘', '명란감자치즈', '바스크치즈케이크', '중화풍오이무침', '항정수육과 미나리무침', '통오징어 나가사끼짬뽕', '마라순두부나베', '배추 조개탕', '미나리생선회무침', '전복파스타(아와비파스타)', '양송이새우감바스', '육전국밥 국내 최초 개발 !! 육전국밥', '육전비빔막국수 국산 메밀과 천연 과일소스의 깊은 맛 !!', '미소곰탕정식 (1인 육전+미소곰탕)', '막국수정식 1인 육전 + 물 or 비빔 막국수)', '소고기육전(대) 한~장 한~장 즉석에서 부치는 대표 메뉴 !!', '수제 소고기 완자 신선한 야채와 소고기로 즉석에서 부치는~', '육전 완자 반반 소고기 육전과 완자를 동시에~', '깻잎전 깻잎 속에 소고기를 넣어 깔끔한 맛!!', '해물김치전 숙성김치와 해물의 조화~', '치즈해물김치전 쫄깃한 모짜렐라 치즈에 숙성김치와 해물의 조화~', '오징어초무침 국내산 오징어를 신선한 야채와 새콤달콤하게~', '소불고기전골(중) 최상급 소고기와 자체개발 특제 양념 육수', '소고기국밥 정식 (1인 육전+소고기국밥)', '소불고기전골(대) 최상급 소고기와 자체개발 특제 양념 육수', '뚝배기불고기 최상급 소고기와 자체개발 특제 양념 육수', '소곱창전골(중) 고소하고 쫄깃한 소 곱창의 매력~', '소곱창전골(대) 고소하고 쫄깃한 소 곱창의 매력~', '육전모둠전골(중) 오직!! 육전국밥에서만 맛볼 수 있는~', '육전모둠전골(대) 오직!! 육전국밥에서만 맛볼 수 있는~', '소고기육전(소) 한~장 한~장 즉석에서 부치는 대표 메뉴 !!', '모둠전 막걸리가 생각나는 즉석 6종 모둠 전', '치즈해물파전 쫄깃한 모짜렐라 치즈에 국내산 오징어와 새우가 듬뿍~', '소고기국밥 하루에도 몇 번 씩 매장에서 직접 끓이는~', '미소곰탕 미소가 저절로 나오는~ 실속 곰탕', '함박곰탕 함박웃음이 저절로 나오는~ 명품 곰탕\r\n(수육+도가니)', '육전 물 막국수 국산 메밀과 천연 과일소스의 시원~한 맛 !!', '양념치킨(국내산)', '후라이드치킨(국내산) 35일산 국내산 신선한 닭고기를 천연 양념 숙성하여 한 마리하고 반마리 더 손님께 제공합니다.', '순살양념', '순살마늘반/순살후라이드반', '순살간장반/순살후라이드반', '블렉페퍼(신메뉴)', '순살블렉페퍼(신메뉴)', '후라이드반/블렉페퍼반', '순살후라이드반/순살블렉

In [ ]:
from langchain_core.prompts import PromptTemplate
from langchain.chat_models import init_chat_model
from langchain_core.output_parsers import StrOutputParser

food_prompt = PromptTemplate.from_template(
    """
너는 메뉴 분류를 잘하는 봇이야.

규칙:
- 주어진 메뉴명과 설명을 보고 대표 메뉴를 한 단어 또는 매우 짧은 명사형으로 정의해.
- 예시:
  - 치즈 돈가스 -> 돈가스
  - 알리오 올리오 -> 파스타
  - 김치찌개 -> 찌개
- 메뉴명과 설명 중 하나가 비어 있으면 남은 정보만 보고 판단해.
- 둘 다 비어있으면 메뉴 없음으로 기재해줘
- 설명 문장, 이유, 부가 설명 없이 답만 한 줄로 출력해.

입력:
{input_text}
"""
)

llm = init_chat_model('gpt-4.1-mini', temperature=0)
output_parser = StrOutputParser()

In [ ]:
# open ai api 활용해서 메뉴명 > 음식명으로 변경
from langchain_core.output_parsers import StrOutputParser

# 1. 체인 정의 (한 번만)
chain = food_prompt | llm | StrOutputParser()


# 2. batch 처리 함수
def prompt_menu_batch(concat_list, batch_size=20):
    inputs = [{"input_text": m} for m in concat_list]

    prompted_menu = []

    for i in range(0, len(inputs), batch_size):
        batch = inputs[i:i+batch_size]
        results = chain.batch(batch)
        prompted_menu.extend([r.strip() for r in results])

    return prompted_menu

In [ ]:
prompted_menu = prompt_menu_batch(concat)

In [ ]:
# 음식 분류에서 중복 제거
food_list = list(set(prompted_menu))

In [ ]:
# 메뉴 설명 생성
llm = init_chat_model('gpt-4.1-mini', temperature=0)
prompt = PromptTemplate.from_template("""
당신은 음식 메뉴 데이터를 정리하는 전문가다.

주어진 메뉴명을 보고, 해당 음식의 특징, 대표적인 맛, 일반적으로 알려진 영양적 특성을 바탕으로
1~3문장의 짧은 설명 문단을 작성하라.

작성 규칙:
1. 반드시 한국어로 작성한다.
2. 메뉴명에 대한 설명만 작성하고, 불필요한 서론이나 추측성 표현은 쓰지 않는다.
3. 음식의 핵심 재료, 조리 방식, 대표적인 맛의 특징을 자연스럽게 포함한다.
4. 일반적으로 알려진 영양 정보를 포함한다. 예: 단백질이 풍부함, 탄수화물 비중이 높음, 나트륨이 높을 수 있음 등
5. 문장은 1~3문장으로만 작성한다.
6. 출력은 설명 문단만 작성한다. 제목, 번호, 따옴표, 불릿포인트는 금지한다.
7. 메뉴명이 너무 일반적이거나 정보가 불충분한 경우에는, 한국에서 일반적으로 떠올릴 수 있는 대표적인 음식 기준으로 설명한다.
8. 허위로 매우 구체적인 수치(칼로리, g 단위 등)는 만들지 말고, 일반적인 수준에서 설명한다.

예시 1
입력: 김치찌개
출력: 김치찌개는 발효된 김치와 돼지고기 또는 참치 등을 넣어 끓인 한국의 대표적인 찌개로, 얼큰하고 감칠맛 나는 국물 맛이 특징이다. 재료에 따라 단백질을 보충할 수 있지만, 김치와 양념이 들어가 나트륨 함량은 다소 높을 수 있다.

예시 2
입력: 비빔밥
출력: 비빔밥은 밥 위에 다양한 나물, 고기, 계란, 고추장을 곁들여 비벼 먹는 음식으로, 여러 재료가 어우러져 조화로운 맛과 식감을 낸다. 탄수화물, 단백질, 채소를 함께 섭취할 수 있어 비교적 균형 잡힌 한 끼가 될 수 있다.

예시 3
입력: 치킨마요덮밥
출력: 치킨마요덮밥은 밥 위에 닭고기와 마요네즈 소스를 올려 먹는 덮밥으로, 고소하고 짭짤한 맛이 강한 편이다. 탄수화물과 단백질을 함께 섭취할 수 있지만, 소스 사용량에 따라 지방과 열량이 높아질 수 있다.

이제 다음 메뉴에 대해 작성하라.

입력: {menu_name}
출력:
""")

output_parser = StrOutputParser()

chain = prompt | llm | output_parser

In [ ]:
# open ai api 활용해서 음식을 해석
# chain은 이미 정의되어 있다고 가정
# chain = prompt | llm | StrOutputParser()

def prompt_food_batch(food_list, batch_size=20):
    inputs = [{"menu_name": f} for f in food_list]

    prompted_food = []

    for i in range(0, len(inputs), batch_size):
        batch = inputs[i:i+batch_size]
        results = chain.batch(batch)
        prompted_food.extend([r.strip() for r in results])

    return prompted_food

In [ ]:
prompted_food = prompt_food_batch(food_list)

In [ ]:
# embedding > Blob 변환까지 포함해서 반환
from openai import OpenAI
import numpy as np

client = OpenAI()

def embed_food(instr: str):
    # 빈값 처리
    if instr is None or str(instr).strip() == "":
        return None

    # 1. 문단 임베딩
    response = client.embeddings.create(
        model="text-embedding-3-small",
        input=instr
    )
    embedding = response.data[0].embedding   # list[float]

    # 2. numpy array(float32) 변환
    arr = np.array(embedding, dtype=np.float32)

    # 3. BLOB(bytes) 변환
    blob = arr.tobytes()

    return blob

In [ ]:
embedded_food = []

for f in prompted_food:
    embedded_food.append(embed_food(f))

In [ ]:
# dataframe으로 합치기

# food_code 만들기
key = range(len(food_list))
key = ["FOD" + (4-len(str(k))) * "0" + str(k) for k in key]

# dataframe용 dict
df_dict = {
    "food_code": key,
    "name": food_list,
    "description": prompted_food,
    "embedding": embedded_food
}

food_df = pd.DataFrame(df_dict)
food_df.head()

,food_code,name,description,embedding
0,FOD0000,토마토,"토마토는 신선한 과일로서 생으로 먹거나 요리에 활용되며, 상큼하고 약간의 단맛과 산...",b'\x00\xe0\xb6<\x00`L<\x00\xc0\x88\xbd\x00@\x8...
1,FOD0001,해물탕,"해물탕은 다양한 해산물과 채소를 매운 국물에 끓여 만든 한국식 해산물 찌개로, 시원...",b'\x00\x80\x8d<\x00\xc0\xd3\xbb\x00\xa0\xd8<\x...
2,FOD0002,스무디,"스무디는 과일이나 채소를 갈아 만든 음료로, 신선한 재료의 자연스러운 단맛과 상큼한...",b'\x00\x80P<\x00\xc0.\xbc\x00`\xe1\xbc\x00@m;\...
3,FOD0003,불고기,"불고기는 얇게 썬 소고기를 간장, 설탕, 마늘, 참기름 등으로 양념해 구워 먹는 한...",b'\x00\xa0\xd1<\x00`\xd7<\x00@2\xbd\x00\x00\x8...
4,FOD0004,조림,"조림은 고기, 생선, 채소 등을 간장과 설탕, 향신료로 졸여 만든 요리로, 짭짤하고...",b'\x00\x00\xb0<\x00\xc0\x98;\x00\xa0J\xbd\x00 ...

In [ ]:
mapping = dict(zip(food_df["name"], food_df["food_code"]))
mapped_list = [mapping.get(p) for p in prompted_menu]
menu_df["food_code"] = mapped_list

In [ ]:
menu_df

,menu_code,restaurant_code,name,price,description,menu_desc,prompted_description,embedding_blobX,embedding,food_code
0,MEN0000,RES0000,회전초밥,,,회전초밥,회전초밥은 신선한 재료로 만든 다양한 초밥을 회전 컨베이어 벨트 위에서 편리하게 즐...,"[0.01146697998046875, -0.041229248046875, -0.0...",AOA7PADgKL0AYNS7ACAgPACAnzwAAO67AAC8uwBA5zwAII...,FOD0047
1,MEN0001,RES0000,장어초밥,,,장어초밥,"장어초밥은 부드럽고 고소한 장어가 신선한 초밥 위에 올려져 깊은 풍미를 자랑하며, ...","[-0.0072174072265625, -0.06524658203125, -0.00...",AIDsuwCghb0AoBe8AEBdPAAAZD0AAKq8AEBQuwDgET0AYP...,FOD0047
2,MEN0002,RES0001,프레지에 1호 홀케이크,50000.0,,프레지에 1호 홀케이크,"프레지에 1호 홀케이크는 신선한 재료로 정성껏 만든 부드럽고 촉촉한 케이크로, 특별...","[0.0193634033203125, -0.00444793701171875, -0....",AKCePADAkbsA4BS9AACeuwAgrz0AIBK9AOACvQDA9jwAIC...,FOD0152
3,MEN0003,RES0001,프레지에,10500.0,,프레지에,"프레지에는 부드러운 크림과 신선한 과일이 조화를 이루는 디저트로, 상큼하면서도 달콤...","[-0.0011615753173828125, -0.0180511474609375, ...",AECYugDgk7wAIIC9ACC8PABAFT0AIOE8AKBnvACAxT0AQJ...,FOD0152
4,MEN0004,RES0001,페르디셔 압펠,6000.0,,페르디셔 압펠,"페르디셔 압펠은 신선한 사과의 상큼한 맛과 부드러운 식감이 조화를 이루는 메뉴로, ...","[0.01401519775390625, -0.019989013671875, -0.0...",AKBlPADAo7wAoBO9AIBQvAAgqzwAwKK6AIAdvAAgQD0AYK...,FOD0046
...,...,...,...,...,...,...,...,...,...,...
2003,MEN2003,RES0099,한우곱창전골,30000.0,인기메뉴! 푸짐하고얼큰한 곱창전골,한우곱창전골 인기메뉴! 푸짐하고얼큰한 곱창전골,"한우곱창전골은 푸짐한 한우 곱창과 얼큰한 국물이 어우러진 인기 메뉴로, 깊고 진한 ...","[0.025177001953125, 0.0005536079406738281, -0....",AEDOPAAgEToAACu8AMAePQCANzwAgFy9AEBgvAAAmzwAoK...,FOD0016
2004,MEN2004,RES0099,육회한접시,17000.0,한우육회,육회한접시 한우육회,"육회한접시는 신선한 한우육회를 사용해 부드럽고 고소한 맛이 특징이며, 고급스러운 한...","[0.0066070556640625, -0.01983642578125, -0.014...",AIDYOwCAorwAIHS8AIDfOQAgNbwAAPK8AAA0vQCAkz0AYB...,FOD0224
2005,MEN2005,RES0099,미니육회,12000.0,한우육회100g,미니육회 한우육회100g,미니육회는 신선한 한우육회 100g으로 구성되어 부드럽고 고소한 맛을 즐길 수 있는...,"[0.01235198974609375, -0.0433349609375, -0.044...",AGBKPACAMb0AQDe9AGBFPADgc7wAIIC9AMDWuwDAYz0AoP...,FOD0224
2006,MEN2006,RES0099,한우곱창 해장국,10000.0,,한우곱창 해장국,한우곱창 해장국은 진한 국물에 부드러운 한우 곱창이 어우러져 깊고 고소한 맛을 자랑...,"[0.00717926025390625, -0.035186767578125, 0.02...",AEDrOwAgEL0A4Oo8AEB0PQAgqDwAYDO9AEDpvAAgQD0AwF...,FOD0068
2007,MEN2007,RES0099,한우육회비빔밥,10000.0,,한우육회비빔밥,한우육회비빔밥은 신선한 한우 육회와 다양한 채소가 어우러져 고소하고 담백한 맛을 자...,"[0.0168609619140625, -0.06182861328125, -0.011...",ACCKPABAfb0AAEC8AOCAOgDAYjwAIDS9AECKOwAAqzwA4I...,FOD0036

컬럼 순서 정렬

In [ ]:
# 1. embedding_blobX 삭제
menu_df = menu_df.drop(columns=['embedding_blobX'], errors='ignore')

# 2. food_code를 restaurant_code 뒤(세번째 위치)로 이동
cols = list(menu_df.columns)

# food_code 먼저 제거 (중복 방지)
cols.remove('food_code')

# restaurant_code 위치 찾기
idx = cols.index('restaurant_code')

# 그 다음 위치에 삽입
cols.insert(idx + 1, 'food_code')

# 컬럼 순서 재정렬
menu_df = menu_df[cols]

In [ ]:
menu_df.to_csv("menu.csv", index=False, encoding="utf-8-sig")

In [ ]:
food_df

,food_code,name,description,embedding
0,FOD0000,토마토,"토마토는 신선한 과일로서 생으로 먹거나 요리에 활용되며, 상큼하고 약간의 단맛과 산...",b'\x00\xe0\xb6<\x00`L<\x00\xc0\x88\xbd\x00@\x8...
1,FOD0001,해물탕,"해물탕은 다양한 해산물과 채소를 매운 국물에 끓여 만든 한국식 해산물 찌개로, 시원...",b'\x00\x80\x8d<\x00\xc0\xd3\xbb\x00\xa0\xd8<\x...
2,FOD0002,스무디,"스무디는 과일이나 채소를 갈아 만든 음료로, 신선한 재료의 자연스러운 단맛과 상큼한...",b'\x00\x80P<\x00\xc0.\xbc\x00`\xe1\xbc\x00@m;\...
3,FOD0003,불고기,"불고기는 얇게 썬 소고기를 간장, 설탕, 마늘, 참기름 등으로 양념해 구워 먹는 한...",b'\x00\xa0\xd1<\x00`\xd7<\x00@2\xbd\x00\x00\x8...
4,FOD0004,조림,"조림은 고기, 생선, 채소 등을 간장과 설탕, 향신료로 졸여 만든 요리로, 짭짤하고...",b'\x00\x00\xb0<\x00\xc0\x98;\x00\xa0J\xbd\x00 ...
...,...,...,...,...
318,FOD0318,오뎅탕,"오뎅탕은 어묵과 다양한 채소를 맑은 국물에 끓여 만든 한국식 국물 요리로, 담백하고...",b'\x00\xe0\xa0<\x00\xe0\xad<\x00\xa0z\xbd\x00\...
319,FOD0319,대창,"대창은 소의 큰창자를 깨끗이 손질해 구워 먹는 음식으로, 쫄깃하고 고소한 맛이 특징...",b'\x00\x80\x95=\x00\xc0N<\x00\xe0\xc7;\x00 c<\...
320,FOD0320,가방,"가방은 음식이 아닌 휴대용 물품 보관용품으로, 조리 방식이나 영양적 특성이 없다.",b'\x00\x00\\;\x00\x806=\x00`\xe2<\x00 _<\x00\x...
321,FOD0321,보신탕,"보신탕은 개고기와 다양한 한약재를 넣어 끓인 보양식으로, 진한 국물과 고기의 깊은 ...",b'\x00\xa0\xa6<\x00\xa0\xb1;\x00\x80=\xbd\x00\...
322,FOD0322,닭구이,"닭구이는 닭고기를 양념하거나 소금으로 간해 직화나 오븐에 구워내는 요리로, 겉은 바...",b'\x00\x80\xbb<\x00@\x97\xbc\x00@\xa8<\x00\xc0...

In [ ]:
food_df.to_csv("food.csv", index=False, encoding="utf-8-sig")

In [3]:
import pandas as pd
import base64
import ast

# 1. CSV 읽기
df = pd.read_csv("food.csv")

# 2. str -> bytes -> base64 변환 함수
def convert_embedding(x):
    if pd.isna(x):
        return None

    # str → bytes 복원 ( "b'...'" → b'...' )
    if isinstance(x, str):
        try:
            x = ast.literal_eval(x)
        except:
            return None

    # bytes → base64
    if isinstance(x, (bytes, bytearray)):
        return base64.b64encode(x).decode('utf-8')

    return None

# 3. embedding 컬럼 덮어쓰기
df['embedding'] = df['embedding'].apply(convert_embedding)

# 4. 저장
df.to_csv("food__.csv", index=False, encoding="utf-8-sig")